#!/usr/bin/env python
"""Generate the learning-curve scenarios: each subset size, both training regimes.

Why generated rather than hand-written
--------------------------------------
A curve is ten scenarios that differ in two fields. Writing them by hand invites
the one mistake that would void the whole experiment — a stray difference in
epochs, learning rate or class weighting between two points, which would then be
read as an effect of data size. Generating them makes "everything else is held
fixed" a property of the code instead of a claim in a comment.

Both regimes are generated from the same template, so the fine-tuned and probed
curves differ from each other only in `freeze_backbone` and the learning rate
that has to move with it.

Metrics are deliberately trimmed to integrity and performance. The curve asks how
accuracy scales with training-set size; running Grad-CAM, corruption robustness
and a membership-inference attack ten more times would add runtime and nothing
else. `integrity.split_leakage` stays because every number is conditional on it.

Usage:
    python scripts/make_curve_scenarios.py --sizes 100,500,2000,7014
"""
from __future__ import annotations

import argparse
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent

# Regime -> (suffix, freeze_backbone, learning rate, human label).
#
# The learning rates differ on purpose and are not a free variable: 1e-4 is low
# so fine-tuning does not wash out pretrained features, while a randomly
# initialised head has nothing to preserve and learns far too slowly at that
# rate. 1e-3 was chosen by sweeping on validation (1e-4 -> 0.498, 1e-3 -> 0.551,
# 1e-2 -> 0.549 balanced accuracy). Holding them equal would have produced
# "probing is poor" as an artefact of the shared hyper-parameter.
REGIMES = {
    "finetune": ("ft", False, 0.0001, "fine-tuned"),
    "probe": ("probe", True, 0.001, "linear probe"),
}


def build(base: dict, size: int, regime: str) -> dict:
    suffix, freeze, lr, label = REGIMES[regime]
    sc = yaml.safe_load(yaml.safe_dump(base))          # deep copy

    sc["name"] = f"curve_{suffix}_n{size}"
    sc["training"]["manifest_prefix"] = f"isic_n{size}"
    sc["training"]["freeze_backbone"] = freeze
    sc["training"]["lr"] = lr
    sc["training"]["out_dir"] = "artifacts_training"
    sc["model"]["id"] = f"resnet18-{suffix}-n{size}"
    sc["model"]["weights_path"] = f"artifacts_training/curve_{suffix}_n{size}.pt"

    sc["card"] = {
        "group": "Learning curve — how much data is enough?",
        "lineage": f"ResNet18 · {label}",
        "name": f"ResNet18 {label}, n={size:,}",
        "emoji": "📈",
        "description": (
            f"Trained on {size:,} images drawn from isic_train.csv by lesion, "
            f"{label}, and evaluated on the same 1,493 images as every other run. "
            f"One point on a curve whose question is where more data stops helping."),
    }
    # The curve measures accuracy against training-set size. The other pillars
    # would cost runtime and answer a question nobody asked here.
    sc["metrics"] = ["integrity.split_leakage", "performance.classification"]
    sc.pop("privacy", None)
    return sc


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--template", default="scenarios/skin_cancer_isic.yaml")
    ap.add_argument("--sizes", default="100,500,2000,7014")
    ap.add_argument("--out", default="scenarios")
    a = ap.parse_args()

    base = yaml.safe_load((REPO / a.template).read_text(encoding="utf-8"))
    out_dir = REPO / a.out
    written = []
    for size in (int(x) for x in a.sizes.split(",")):
        for regime in REGIMES:
            sc = build(base, size, regime)
            path = out_dir / f"{sc['name']}.yaml"
            path.write_text(
                "# GENERATED by scripts/make_curve_scenarios.py — edit that, not this.\n"
                "#\n"
                "# One point on the learning curve. Everything except the training\n"
                "# manifest, freeze_backbone and the learning rate is identical across\n"
                "# every point, so a difference between two points can only be the data\n"
                "# size or the regime.\n"
                + yaml.safe_dump(sc, sort_keys=False, allow_unicode=True),
                encoding="utf-8")
            written.append(path.name)

    print(f"▶ wrote {len(written)} scenarios:")
    for name in written:
        print(f"    {name}")
    print("\nTrain and evaluate each with scripts/train_model.py then run_scenario.py.")


if __name__ == "__main__":
    main()
